fix missing stdint.h inclusion, fixes build on musl
src/codegen.c:1542:8: error: unknown type name 'int8_t'
 1542 | static int8_t *g_cm_selfcls = NULL;
      |        ^~~~~~
src/codegen.c: In function 'cmethod_takes_self_cls':
src/codegen.c:1550:21: error: 'int8_t' undeclared (first use in this function)
 1550 |     g_cm_selfcls = (int8_t *)calloc((size_t)c->nscopes, 1);
      |                     ^~~~~~
src/codegen.c:2:1: note: 'int8_t' is defined in header '<stdint.h>'; did you forget to '#include <stdint.h>'?
    1 | #include "codegen_internal.h"
  +++ |+#include <stdint.h>
    2 |
src/codegen.c:1550:21: note: each undeclared identifier is reported only once for each function it appears in
 1550 |     g_cm_selfcls = (int8_t *)calloc((size_t)c->nscopes, 1);
      |                     ^~~~~~